[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cython"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "pygoslin/tests"
]
